import type { LocalizedString } from '../types/month';

export const adminUi: Record<string, LocalizedString> = {
  admin: { ru: 'Администрирование', en: 'Admin Panel', uk: 'Адміністрування' },
  signIn: { ru: 'Войти', en: 'Sign in', uk: 'Увійти' },
  signOut: { ru: 'Выйти', en: 'Sign out', uk: 'Вийти' },
  notAuthorized: { ru: 'У вас нет доступа к админ-панели', en: 'You do not have admin access', uk: 'У вас немає доступу до адмін-панелі' },
  months: { ru: 'Месяцы', en: 'Months', uk: 'Місяці' },
  addMonth: { ru: 'Добавить месяц', en: 'Add month', uk: 'Додати місяць' },
  editMonth: { ru: 'Редактировать месяц', en: 'Edit month', uk: 'Редагувати місяць' },
  submitRequest: { ru: 'Запрос на улучшение', en: 'Improvement request', uk: 'Запит на покращення' },
  reportBug: { ru: 'Сообщить об ошибке', en: 'Report a bug', uk: 'Повідомити про помилку' },
  save: { ru: 'Сохранить', en: 'Save', uk: 'Зберегти' },
  publish: { ru: 'Опубликовать', en: 'Publish', uk: 'Опублікувати' },
  cancel: { ru: 'Отмена', en: 'Cancel', uk: 'Скасувати' },
  title: { ru: 'Заголовок', en: 'Title', uk: 'Заголовок' },
  description: { ru: 'Описание', en: 'Description', uk: 'Опис' },
  year: { ru: 'Год', en: 'Year', uk: 'Рік' },
  month: { ru: 'Месяц', en: 'Month', uk: 'Місяць' },
  themeTitle: { ru: 'Название темы', en: 'Theme title', uk: 'Назва теми' },
  themeDesc: { ru: 'Описание темы', en: 'Theme description', uk: 'Опис теми' },
  guestName: { ru: 'Имя гостя', en: 'Guest name', uk: "Ім'я гостя" },
  guestRole: { ru: 'Роль гостя', en: 'Guest role', uk: 'Роль гостя' },
  guestBio: { ru: 'Биография гостя', en: 'Guest bio', uk: 'Біографія гостя' },
  guestImage: { ru: 'Фото гостя', en: 'Guest photo', uk: 'Фото гостя' },
  sectionTitle: { ru: 'Название раздела', en: 'Section title', uk: 'Назва розділу' },
  sectionDesc: { ru: 'Описание раздела', en: 'Section description', uk: 'Опис розділу' },
  addSection: { ru: 'Добавить раздел', en: 'Add section', uk: 'Додати розділ' },
  removeSection: { ru: 'Удалить', en: 'Remove', uk: 'Видалити' },
  closingMessage: { ru: 'Завершающее сообщение', en: 'Closing message', uk: 'Завершальне повідомлення' },
  setAsCurrent: { ru: 'Сделать текущим месяцем', en: 'Set as current month', uk: 'Зробити поточним місяцем' },
  issueTitle: { ru: 'Тема', en: 'Subject', uk: 'Тема' },
  issueBody: { ru: 'Описание', en: 'Description', uk: 'Опис' },
  autoImplement: { ru: 'Автоматически реализовать (Claude Code)', en: 'Auto-implement (Claude Code)', uk: 'Автоматично реалізувати (Claude Code)' },
  submit: { ru: 'Отправить', en: 'Submit', uk: 'Надіслати' },
  success: { ru: 'Успешно!', en: 'Success!', uk: 'Успішно!' },
  saving: { ru: 'Сохранение...', en: 'Saving...', uk: 'Збереження...' },
  ru: { ru: 'Русский', en: 'Russian', uk: 'Російська' },
  en: { ru: 'Английский', en: 'English', uk: 'Англійська' },
  uk: { ru: 'Украинский', en: 'Ukrainian', uk: 'Українська' },
};
